### ISSUE TITLE
How to run this application?

### ISSUE THREAD

**Issue by mh-github** [rdeits/cryptics#18]
$ rake server
rake aborted!
Don't know how to build task 'server'

(See full trace by running task with --trace)

$ which rake
/home/mh/.rvm/rubies/ruby-2.3.1/bin/rake

 $ rake --version
rake, version 10.4.2

$ pip install rake
Collecting rake
  Using cached rake-1.0.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/rake.egg-info
    writing requirements to pip-egg-info/rake.egg-info/requires.txt
    writing pip-egg-info/rake.egg-info/PKG-INFO
    writing namespace_packages to pip-egg-info/rake.egg-info/namespace_packages.txt
    writing top-level names to pip-egg-info/rake.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/rake.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/rake.egg-info/SOURCES.txt'
    error: Namespace package problem: rake is a namespace package, but its
    __init__.py does not call declare_namespace()! Please fix it.
    (See the setuptools manual under "Namespace Packages" for details.)
    "
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-1G6Rzx/rake/

**Comment by rdeits** [comment]
Ah, sorry, looks like a typo in the readme. Try `rake serve` instead of`rake server`

I've updated the readme too.

**Comment by mh-github** [comment]
rake serve throws a different error:

python -m web.template --compile templates
python pycryptics/crypticweb/server.py
Traceback (most recent call last):
  File "pycryptics/crypticweb/server.py", line 2, in <module>
    from pycryptics.solve_clue import CrypticClueSolver, split_clue_text
ImportError: No module named pycryptics.solve_clue
rake aborted!
Command failed with status (1): [python pycryptics/crypticweb/server.py...]
/home/mh/Code/Python/cryptics/Rakefile:16:in `block in <top (required)>'
Tasks: TOP => serve
(See full trace by running task with --trace)

**Comment by rdeits** [comment]
That's odd. I just a clean install following the instructions from the Readme and everything is working. What Python version are you using, and what folder are you running `rake serve` from?

**Comment by mh-github** [comment]
cryptics $ python --version
Python 2.7.12

Cloned the repository, followed the instructions. Running rake serve from cryptics folder, using Python 2.7.12, the error is:
cryptics $ rake serve
python -m web.template --compile templates
python pycryptics/crypticweb/server.py
Traceback (most recent call last):
  File "pycryptics/crypticweb/server.py", line 2, in <module>
    from pycryptics.solve_clue import CrypticClueSolver, split_clue_text
ImportError: No module named pycryptics.solve_clue
rake aborted!
Command failed with status (1): [python pycryptics/crypticweb/server.py...]
/home/mh/Code/Python/cryptics/Rakefile:16:in `block in <top (required)>'
Tasks: TOP => serve
(See full trace by running task with --trace)

Pls note: I am not using virtualenv

**Comment by rdeits** [comment]
I'm very confused why this isn't working for you. Can you please try adding the cryptics folder (that is, the folder which contains `pycryptics`) to your pythonpath? E.g.

```
export PYTHONPATH="$PYTHONPATH:/path/to/wherever/you/downloaded/cryptics"
```

**Comment by mh-github** [comment]
Yes, it was PYTHONPATH. The value was not set.

$ echo $PYTHONPATH

$ export PYTHONPATH="/home/mh/Code/Python/cryptics"
$ rake serve
python -m web.template --compile templates
python pycryptics/crypticweb/server.py
Loading indicators from file...
...done.
Starting up server. Press Ctrl+c to shut down
http://0.0.0.0:8080/
127.0.0.1:55908 - - [17/Oct/2017 16:51:43] "HTTP/1.1 GET /" - 200 OK
